DEFINES += DEEPIN_CLONE_UID=\\\"DEEPIN_CLONE_UID\\\"\
           DEEPIN_CLONE_OPEN_DIALOG=\\\"DEEPIN_CLONE_OPEN_DIALOG\\\"\
           DEEPIN_CLONE_OPEN_URL=\\\"DEEPIN_CLONE_OPEN_URL\\\"\
           DEEPIN_CLONE_PARENT_WINID=\\\"DEEPIN_CLONE_PARENT_WINID\\\"\
           DEEPIN_CLONE_TITLE=\\\"DEEPIN_CLONE_TITLE\\\"\
           DEEPIN_CLONE_FILE_NAME=\\\"DEEPIN_CLONE_FILE_NAME\\\"\
           DEEPIN_CLONE_NAME_FILTER=\\\"DEEPIN_CLONE_NAME_FILTER\\\"\
           DEEPIN_CLONE_GET_FILE=\\\"DEEPIN_CLONE_GET_FILE\\\"\
           DEEPIN_CLONE_SHOW_FILE=\\\"DEEPIN_CLONE_SHOW_FILE\\\"
